export const landingCopy = {
  uz: {
    eyebrow: 'ISH VA HAYOT. SIZNING RITMINGIZDA.',
    headingA: 'Vaqtingizga mos.',
    headingB: 'Sizga mos ish.',
    intro:
      'Kuningizni ishga emas, ishni kuningizga moslang. Qulay smenalar, ochiq shartlar va aniq kelishuvlar — barchasi bir joyda.',
    scroll: 'Imkoniyatlarni kashf eting',
    free: 'Boshlash bepul',
    planner: 'Sizning kuningiz',
    plannerSubtitle: 'Ish va hayot bir rejada',
    personal: 'O‘zingiz uchun vaqt',
    timeChoice: 'Qaysi payt sizniki?',
    allClear: 'Shartlar oldindan aniq',
    payment: 'Kelishilgan ish haqi',
    offer: 'Taklif → Sizning tasdig‘ingiz',
    noRush: 'Tanlov har doim sizniki.',
    schedule: 'Siz tanlaysiz. Reja moslashadi.',
    flexibility: 'O‘zingizga mos vaqt',
    flexibilityText: 'Bir kunlik yoki soatbay — kuningizga joylashtiring.',
    clarity: 'Ochiq shartlar',
    clarityText: 'Vaqt, vazifa va ish haqini avvaldan biling.',
    control: 'Hammasi bir joyda',
    controlText: 'Arizadan ish yakunigacha holatni kuzating.',
    opportunity: 'KEYINGI IMKONIYATINGIZ',
    opportunitiesA: 'Yangi smena.',
    opportunitiesB: 'Yangi imkoniyat.',
    opportunitiesText: 'Yangi smenalarni ko‘ring. Vaqti, manzili va shartlarini solishtiring.',
    categoriesUnavailable:
      'Ish turlari hozircha yuklanmadi. Barcha smenalarni ko‘rishingiz mumkin.',
    all: 'Barchasi',
    details: 'Kichik tafsilotlar.',
    difference: 'Katta qulaylik.',
    benefitsLabel: 'SIZ UCHUN O‘YLANGAN',
    balance: 'Ish. O‘qish. Hayot.',
    balanceLine: 'Bir rejada.',
    balanceText: 'Bo‘sh vaqtingizni belgilang. Qolgan rejalarni o‘zgartirmasdan smena tanlang.',
    week: 'Sizning haftangiz',
    study: 'O‘qish',
    life: 'Shaxsiy vaqt',
    shift: 'Smena',
    before: 'Shartlar avval.',
    after: 'Qaror keyin.',
    clarityCardText: 'Tushunarli ma’lumot bilan xotirjam tanlov qiling.',
    requirements: 'Vazifa va talablar',
    employer: 'Ish beruvchi ma’lumoti',
    payTime: 'Ish haqi va vaqt',
    consentA: 'Siz tasdiqlaysiz.',
    consentB: 'Rejangizga tushadi.',
    consentText:
      'Ariza — bu boshlanish. Faqat taklifni qabul qilganingizdan keyin smena tasdiqlanadi.',
    stepsLabel: 'BIRINCHI SMENAGACHA',
    stepsTitle: 'Boshlash oson.',
    stepsText: 'Oddiy qadamlar. Tushunarli jarayon.',
    businessLabel: 'SMENATOP BIZNES',
    businessA: 'Jamoani toping.',
    businessB: 'Vaqtni tejang.',
    businessText:
      'Smenalarni bir joyda rejalashtiring. Nomzodlarni ko‘ring, taklif yuboring va davomatni kuzating.',
    businessPreview: 'Taqvim namunasi',
    weekPlan: 'Haftalik reja',
    team: 'Jamoa',
    planned: 'Rejalashtirilgan',
    seePlans: 'Tariflarni ko‘rish',
    faqLabel: 'BILIB OLISH FOYDALI',
    faqTitle: 'Savolingiz bormi?',
    faqSubtitle: 'Eng kerakli javoblar shu yerda.',
    questions: [
      [
        'Ishchi uchun foydalanish bepulmi?',
        'Ha. Ishchi profil yaratishi, smenalarni ko‘rishi va ariza yuborishi uchun platforma to‘lovi olinmaydi. Ish beruvchilar uchun obuna tariflari alohida.',
      ],
      [
        'Ish haqi qanday to‘lanadi?',
        'Mehnat haqini ish beruvchi bevosita to‘laydi. Platformada kelishilgan summa, ish vaqti va tomonlarning to‘lov tasdiqlari qayd etiladi.',
      ],
      [
        'Ariza yuborsam, smena darhol tasdiqlanadimi?',
        'Avval ish beruvchi taklif yuboradi. Taklif joyni band qilmaydi: u amalda bo‘lsa va bo‘sh joy qolgan bo‘lsa, uni qabul qilganingizdan keyin smena tasdiqlanadi va jadvalingizda paydo bo‘ladi.',
      ],
      [
        'Biznes sifatida qanday boshlayman?',
        'Telefon orqali kiring, tashkilot va filial ma’lumotlarini to‘ldiring. Tashkilot tekshiruvi va tegishli obuna shartlaridan keyin smena e’lon qilishingiz mumkin.',
      ],
    ],
    finalA: 'Keyingi qadamingiz',
    finalB: 'shu yerdan boshlanadi.',
    finalText: 'O‘zingizga mos smenani toping. Kuningizni o‘zingiz boshqaring.',
    mobileNote: 'Sizga mos ishni toping',
    mobileAction: 'Smenalarni ko‘rish',
    weekdays: ['D', 'S', 'Ch', 'P', 'J', 'Sh', 'Y'],
  },
  ru: {
    eyebrow: 'РАБОТА И ЖИЗНЬ. В ВАШЕМ РИТМЕ.',
    headingA: 'Ваше время.',
    headingB: 'Ваша работа.',
    intro:
      'Подбирайте работу под свою жизнь. Удобные смены, понятные условия и ясные договорённости — в одном месте.',
    scroll: 'Откройте новые возможности',
    free: 'Начните бесплатно',
    planner: 'Ваш день',
    plannerSubtitle: 'Работа и жизнь в одном плане',
    personal: 'Время для себя',
    timeChoice: 'Когда вам удобно?',
    allClear: 'Условия известны заранее',
    payment: 'Согласованная оплата',
    offer: 'Предложение → Ваше согласие',
    noRush: 'Выбор всегда за вами.',
    schedule: 'Вы выбираете. План меняется.',
    flexibility: 'Удобное вам время',
    flexibilityText: 'На день или на несколько часов — впишите в свой план.',
    clarity: 'Понятные условия',
    clarityText: 'Узнайте время, задачи и оплату заранее.',
    control: 'Всё в одном месте',
    controlText: 'Следите за статусом от заявки до завершения.',
    opportunity: 'ВАША СЛЕДУЮЩАЯ ВОЗМОЖНОСТЬ',
    opportunitiesA: 'Новая смена.',
    opportunitiesB: 'Новые возможности.',
    opportunitiesText: 'Посмотрите новые смены. Сравните время, адрес и условия.',
    categoriesUnavailable: 'Не удалось загрузить категории. Все смены по-прежнему доступны.',
    all: 'Все',
    details: 'Маленькие детали.',
    difference: 'Большое удобство.',
    benefitsLabel: 'ПРОДУМАНО ДЛЯ ВАС',
    balance: 'Работа. Учёба. Жизнь.',
    balanceLine: 'В одном плане.',
    balanceText: 'Укажите свободное время. Выберите смену, сохранив остальные планы.',
    week: 'Ваша неделя',
    study: 'Учёба',
    life: 'Личное время',
    shift: 'Смена',
    before: 'Сначала условия.',
    after: 'Потом решение.',
    clarityCardText: 'Выбирайте спокойно, зная важные детали.',
    requirements: 'Задачи и требования',
    employer: 'Информация о работодателе',
    payTime: 'Оплата и время',
    consentA: 'Вы подтверждаете.',
    consentB: 'Смена в вашем плане.',
    consentText:
      'Заявка — только начало. Смена подтверждается лишь после вашего согласия на предложение.',
    stepsLabel: 'ДО ПЕРВОЙ СМЕНЫ',
    stepsTitle: 'Начать просто.',
    stepsText: 'Простые шаги. Понятный процесс.',
    businessLabel: 'SMENATOP ДЛЯ БИЗНЕСА',
    businessA: 'Найдите команду.',
    businessB: 'Сохраните время.',
    businessText:
      'Планируйте смены в одном месте. Выбирайте кандидатов, отправляйте предложения и следите за посещаемостью.',
    businessPreview: 'Пример календаря',
    weekPlan: 'План на неделю',
    team: 'Команда',
    planned: 'Запланировано',
    seePlans: 'Посмотреть тарифы',
    faqLabel: 'ПОЛЕЗНО ЗНАТЬ',
    faqTitle: 'Есть вопросы?',
    faqSubtitle: 'Самые важные ответы — здесь.',
    questions: [
      [
        'Для работника это бесплатно?',
        'Да. Создание профиля, поиск смен и подача заявок бесплатны для работника. Для работодателей предусмотрены отдельные тарифы подписки.',
      ],
      [
        'Как выплачивается зарплата?',
        'Работодатель оплачивает труд напрямую. Платформа фиксирует согласованную сумму, рабочее время и подтверждения оплаты обеих сторон.',
      ],
      [
        'Заявка сразу подтверждает смену?',
        'Сначала работодатель отправляет предложение. Оно не резервирует место: если предложение ещё действует и осталось свободное место, после вашего согласия смена подтверждается и появляется в расписании.',
      ],
      [
        'Как начать бизнесу?',
        'Войдите по номеру телефона и заполните информацию об организации и филиале. После проверки организации и выполнения условий подписки можно публиковать смены.',
      ],
    ],
    finalA: 'Ваш следующий шаг',
    finalB: 'начинается здесь.',
    finalText: 'Найдите подходящую смену. Управляйте своим днём.',
    mobileNote: 'Работа в вашем ритме',
    mobileAction: 'Посмотреть смены',
    weekdays: ['Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Вс'],
  },
} as const;
