export const organizationProfileCopy = {
  uz: {
    eyebrow: 'ISH BERUVCHI PROFILI',
    title: 'Kompaniya profili',
    intro:
      'Kompaniya ma’lumotlari, aloqa va ishchilar ko‘radigan asosiy ma’lumotlarni bir joyda boshqaring.',
    edit: 'Profilni tahrirlash',
    preview: 'Profil ko‘rinishi',
    save: 'O‘zgarishlarni saqlash',
    saving: 'Saqlanmoqda…',
    cancel: 'Bekor qilish',
    saved: 'Kompaniya profili saqlandi.',
    unsaved: 'Saqlanmagan o‘zgarishlar',
    unchanged: 'Hozircha o‘zgarish yo‘q',
    editing: 'Profilni tahrirlash',
    editingHint: 'Ma’lumotlar faqat saqlaganingizdan keyin yangilanadi.',
    identity: 'Kompaniya haqida asosiy ma’lumot',
    identityHint: 'Nom va shahar smenalarda ish beruvchini tanishga yordam beradi.',
    name: 'Tashkilot nomi',
    nameHint: 'Ishchilar smenalarda shu nomni ko‘radi.',
    stir: 'STIR',
    stirHint: '9 ta raqam. Agar mavjud bo‘lsa kiriting.',
    city: 'Shahar',
    selectCity: 'Shaharni tanlang',
    contact: 'Aloqa ma’lumotlari',
    contactHint: 'Tashkilot nomidan muloqot qiladigan mas’ul shaxs.',
    contactName: 'Aloqa shaxsi',
    contactPhone: 'Aloqa telefoni',
    phoneHint: 'Mamlakat kodi bilan, masalan +998901234567. Bu ichki aloqa ma’lumoti.',
    website: 'Veb-sayt',
    websiteHint: 'https:// bilan boshlangan kompaniya manzili.',
    about: 'Kompaniya tavsifi',
    aboutHint:
      'Nima bilan shug‘ullanasiz va siz bilan ishlash qanday? Qisqa, aniq ma’lumot yozing.',
    description: 'Kompaniya haqida',
    descriptionPlaceholder: 'Faoliyatingiz, jamoangiz va ish sharoitlari haqida yozing…',
    optional: 'ixtiyoriy',
    empty: 'Kiritilmagan',
    characters: 'belgi',
    identityReview:
      'Nom, STIR yoki shahar o‘zgarsa, kompaniya ma’lumotlari qayta tekshiruvga yuborilishi mumkin.',
    invalidName: '2–150 ta belgidan iborat tashkilot nomini kiriting.',
    invalidContact: 'Aloqa shaxsining ismini 2–100 ta belgi bilan kiriting.',
    invalidCity: 'Shaharni tanlang.',
    invalidStir: 'STIR 9 ta raqamdan iborat bo‘lishi kerak.',
    invalidPhone: 'Telefonni + va mamlakat kodi bilan to‘liq kiriting.',
    invalidWebsite: 'To‘g‘ri http:// yoki https:// manzilini kiriting (500 belgigacha).',
    invalidDescription: 'Tavsif 3 000 belgidan oshmasligi kerak.',
    fixErrors: 'Belgilangan maydonlarni tekshiring.',
    conflict: 'Profil boshqa joyda yangilangan. Siz kiritgan matn saqlash oynasida qolgan.',
    conflictHint:
      'So‘nggi ma’lumotlarni yangilang va pastdagi saqlangan profil bilan solishtiring. Bekor qilish so‘nggi nusxaga qaytaradi; keyin tahrirlashni qayta boshlashingiz mumkin.',
    refresh: 'Saqlangan ma’lumotlarni yangilash',
    refreshNotice:
      'Saqlangan ma’lumotlarni yangilab bo‘lmadi. Kiritgan o‘zgarishlaringiz joyida qolgan.',
    discardTitle: 'O‘zgarishlarni bekor qilasizmi?',
    discardText:
      'Saqlanmagan tahrirlar o‘chadi. Serverda saqlangan kompaniya ma’lumotlari o‘zgarmaydi.',
    keepEditing: 'Tahrirlashda qolish',
    discard: 'O‘zgarishlarni bekor qilish',
    readOnly:
      'Siz kompaniya profilini ko‘rishingiz mumkin. Tahrirlash uchun tashkilotni boshqarish huquqi kerak.',
    suspended:
      'Profil cheklangan. Ma’lumotlarni o‘zgartirishdan oldin yordam xizmatiga murojaat qiling.',
    noOrg: 'Avval tashkilot tanlang',
    noOrgText: 'Profil, filiallar va obuna ma’lumotlari tanlangan tashkilotga tegishli bo‘ladi.',
    chooseOrg: 'Ish maydonini tanlash',
    createOrg: 'Tashkilot yaratish',
    completeness: 'Profilning to‘liqligi',
    completed: 'band to‘ldirilgan',
    completenessHint:
      'Faqat saqlangan ma’lumotlar hisoblanadi. Bu tekshiruv yoki ishga qabul kafolati emas.',
    checklistName: 'Kompaniya nomi',
    checklistCity: 'Faoliyat shahri',
    checklistContact: 'Mas’ul aloqa shaxsi',
    checklistChannel: 'Telefon yoki veb-sayt',
    checklistAbout: 'Kompaniya tavsifi',
    checklistBranch: 'Manzilli faol filial',
    complete: 'To‘ldirilgan',
    missing: 'To‘ldirish tavsiya etiladi',
    verification: 'Tekshiruv holati',
    verifiedText: 'Kompaniya SmenaTop tekshiruvidan o‘tgan.',
    pendingText: 'So‘rov SmenaTop jamoasi ko‘rib chiqishida. Natija holatda aks etadi.',
    rejectedText: 'Ma’lumotlarni tekshiring va kerakli tuzatishlardan keyin qayta yuboring.',
    unverifiedText: 'Ma’lumotlaringizni to‘ldirib, SmenaTop tekshiruviga yuboring.',
    verificationSubmit: 'Tekshiruvga yuborish',
    verificationHint: 'Kompaniya profili va tekshiruv holati alohida boshqariladi.',
    billing: 'Obuna va foydalanish',
    billingReadOnly: 'Obuna ma’lumotlari moliyaviy ko‘rish huquqiga ega a’zolar uchun ochiladi.',
    billingNone: 'Amaldagi obuna huquqi topilmadi.',
    billingActive: 'Amaldagi foydalanish davri',
    billingUntil: 'Davr yakuni',
    billingLimit: 'Davr uchun e’lon limiti',
    billingManage: 'Obunani ko‘rish',
    billingSeparate: 'Platforma obunasi ishchilarning mehnat haqidan alohida.',
    access: 'Sizning kirishingiz',
    scopeAll: 'Tashkilot bo‘yicha',
    scopeBranches: 'Biriktirilgan filiallar doirasida',
    manageProfile: 'Profilni boshqarish',
    manageTeam: 'Jamoa va filiallar',
    viewBilling: 'Obunani ko‘rish',
    allowed: 'Ruxsat bor',
    restricted: 'Ruxsat yo‘q',
    branches: 'Filiallar va jamoa',
    branchesHint: 'Ish joyi manzili har bir filialda alohida saqlanadi.',
    branchCount: 'faol filial',
    memberCount: 'faol jamoa a’zosi',
    branchManage: 'Filiallar va jamoani boshqarish',
    noBranches: 'Bu doirada faol filial yo‘q.',
    branchScope: 'Sizga biriktirilgan filiallar ko‘rsatilgan.',
    previewTitle: 'Saqlangan profil ko‘rinishi',
    previewHint:
      'Saqlangan kompaniya ma’lumotlaridan namuna. Shaxsiy telefon, STIR va hujjatlar bu ko‘rinishga kiritilmaydi.',
    previewEmpty: 'Kompaniya tavsifi hali kiritilmagan.',
    previewArea: 'Faoliyat hududlari',
    documents: 'Tekshiruv hujjatlari',
    documentsHint:
      'Fayllar shaxsiy hisobingizda saqlanadi. Yuklash kompaniya profiliga biriktirish yoki tekshiruv tasdig‘i degani emas.',
    documentsOpen: 'Shaxsiy hujjatlarni ochish',
    documentsClose: 'Hujjatlarni yopish',
    integrations: 'Integratsiyalar va API kalitlari',
    integrationsHint: 'Faqat shu tashkilot doirasidagi ruxsatli integratsiyalar uchun.',
    support: 'Yordam xizmati',
    privacy: 'Maxfiylik',
    terms: 'Foydalanish shartlari',
    roleOwner: 'Tashkilot egasi',
    roleAdmin: 'Administrator',
    roleManager: 'Menejer',
    roleFinance: 'Moliya xodimi',
    roleCustom: 'Maxsus rol',
    catalogFailed:
      'Shaharlar ro‘yxatini yuklab bo‘lmadi. Kiritgan ma’lumotlaringiz saqlash oynasida qoladi.',
  },
  ru: {
    eyebrow: 'ПРОФИЛЬ РАБОТОДАТЕЛЯ',
    title: 'Профиль компании',
    intro:
      'Управляйте данными компании, контактами и основной информацией для работников в одном месте.',
    edit: 'Редактировать профиль',
    preview: 'Вид профиля',
    save: 'Сохранить изменения',
    saving: 'Сохраняем…',
    cancel: 'Отменить',
    saved: 'Профиль компании сохранён.',
    unsaved: 'Есть несохранённые изменения',
    unchanged: 'Изменений пока нет',
    editing: 'Редактирование профиля',
    editingHint: 'Данные изменятся только после сохранения.',
    identity: 'Основные сведения',
    identityHint: 'Название и город помогают узнать работодателя в сменах.',
    name: 'Название организации',
    nameHint: 'Работники видят это название в сменах.',
    stir: 'ИНН (STIR)',
    stirHint: '9 цифр. Укажите, если есть.',
    city: 'Город',
    selectCity: 'Выберите город',
    contact: 'Контактные данные',
    contactHint: 'Ответственный человек, который общается от имени компании.',
    contactName: 'Контактное лицо',
    contactPhone: 'Контактный телефон',
    phoneHint: 'С кодом страны, например +998901234567. Это внутренние контактные данные.',
    website: 'Веб-сайт',
    websiteHint: 'Адрес компании, начинающийся с https://.',
    about: 'Описание компании',
    aboutHint: 'Чем вы занимаетесь и как у вас работать? Напишите кратко и по существу.',
    description: 'О компании',
    descriptionPlaceholder: 'Расскажите о деятельности, команде и условиях работы…',
    optional: 'необязательно',
    empty: 'Не указано',
    characters: 'знаков',
    identityReview:
      'Изменение названия, ИНН или города может отправить данные компании на повторную проверку.',
    invalidName: 'Введите название организации от 2 до 150 знаков.',
    invalidContact: 'Введите имя контактного лица от 2 до 100 знаков.',
    invalidCity: 'Выберите город.',
    invalidStir: 'ИНН должен содержать 9 цифр.',
    invalidPhone: 'Введите полный телефон с + и кодом страны.',
    invalidWebsite: 'Введите корректный адрес http:// или https:// (до 500 знаков).',
    invalidDescription: 'Описание не должно превышать 3 000 знаков.',
    fixErrors: 'Проверьте отмеченные поля.',
    conflict: 'Профиль изменён в другом месте. Ваш текст остался в форме редактирования.',
    conflictHint:
      'Обновите сохранённые данные и сравните с профилем ниже. Отмена вернёт последнюю версию; после этого можно снова начать редактирование.',
    refresh: 'Обновить сохранённые данные',
    refreshNotice: 'Не удалось обновить сохранённые данные. Ваши изменения остаются в форме.',
    discardTitle: 'Отменить изменения?',
    discardText: 'Несохранённые правки будут удалены. Данные компании на сервере не изменятся.',
    keepEditing: 'Продолжить редактирование',
    discard: 'Отменить изменения',
    readOnly:
      'Вы можете просматривать профиль компании. Для редактирования нужно право управления организацией.',
    suspended: 'Профиль ограничен. Обратитесь в поддержку перед изменением данных.',
    noOrg: 'Сначала выберите организацию',
    noOrgText: 'Профиль, филиалы и подписка относятся к выбранной организации.',
    chooseOrg: 'Выбрать рабочее пространство',
    createOrg: 'Создать организацию',
    completeness: 'Заполнение профиля',
    completed: 'пунктов заполнено',
    completenessHint: 'Учитываются только сохранённые данные. Это не проверка и не гарантия найма.',
    checklistName: 'Название компании',
    checklistCity: 'Город работы',
    checklistContact: 'Ответственное контактное лицо',
    checklistChannel: 'Телефон или веб-сайт',
    checklistAbout: 'Описание компании',
    checklistBranch: 'Активный филиал с адресом',
    complete: 'Заполнено',
    missing: 'Рекомендуем заполнить',
    verification: 'Статус проверки',
    verifiedText: 'Компания прошла проверку SmenaTop.',
    pendingText: 'Команда SmenaTop рассматривает запрос. Результат появится в статусе.',
    rejectedText: 'Проверьте данные и отправьте запрос повторно после исправлений.',
    unverifiedText: 'Заполните данные и отправьте компанию на проверку SmenaTop.',
    verificationSubmit: 'Отправить на проверку',
    verificationHint: 'Данные профиля и статус проверки управляются отдельно.',
    billing: 'Подписка и доступ',
    billingReadOnly: 'Данные подписки доступны участникам с правом просмотра финансов.',
    billingNone: 'Действующее право доступа по подписке не найдено.',
    billingActive: 'Действующий период доступа',
    billingUntil: 'Конец периода',
    billingLimit: 'Лимит публикаций за период',
    billingManage: 'Открыть подписку',
    billingSeparate: 'Подписка платформы не связана с зарплатой работников.',
    access: 'Ваш доступ',
    scopeAll: 'По всей организации',
    scopeBranches: 'В назначенных филиалах',
    manageProfile: 'Управление профилем',
    manageTeam: 'Команда и филиалы',
    viewBilling: 'Просмотр подписки',
    allowed: 'Разрешено',
    restricted: 'Нет права',
    branches: 'Филиалы и команда',
    branchesHint: 'Адрес места работы хранится отдельно в каждом филиале.',
    branchCount: 'активных филиалов',
    memberCount: 'активных участников',
    branchManage: 'Управлять филиалами и командой',
    noBranches: 'В этой области доступа нет активных филиалов.',
    branchScope: 'Показаны назначенные вам филиалы.',
    previewTitle: 'Вид сохранённого профиля',
    previewHint:
      'Пример из сохранённых данных компании. Личный телефон, ИНН и документы сюда не включены.',
    previewEmpty: 'Описание компании ещё не добавлено.',
    previewArea: 'Районы работы',
    documents: 'Документы для проверки',
    documentsHint:
      'Файлы хранятся в вашем личном аккаунте. Загрузка не означает привязку к компании или подтверждение проверки.',
    documentsOpen: 'Открыть личные документы',
    documentsClose: 'Скрыть документы',
    integrations: 'Интеграции и API-ключи',
    integrationsHint: 'Только для разрешённых интеграций в пределах этой организации.',
    support: 'Поддержка',
    privacy: 'Конфиденциальность',
    terms: 'Условия использования',
    roleOwner: 'Владелец организации',
    roleAdmin: 'Администратор',
    roleManager: 'Менеджер',
    roleFinance: 'Финансовый сотрудник',
    roleCustom: 'Особая роль',
    catalogFailed: 'Не удалось загрузить города. Введённые данные остаются в форме редактирования.',
  },
};
export type OrganizationProfileCopy = typeof organizationProfileCopy.uz;
