export const workspaceCopy = {
  uz: {
    candidates: 'Nomzodlar',
    candidateIntro: 'Arizalarni solishtiring, profilni ko‘ring va keyingi qarorni qabul qiling.',
    applicationsIntro: 'Har bir arizangizning holati va keyingi qadami bir joyda.',
    all: 'Barchasi',
    active: 'Jarayonda',
    offers: 'Takliflar',
    accepted: 'Tasdiqlangan',
    closed: 'Yakunlangan',
    candidateSearch: 'Ism, tajriba yoki smena bo‘yicha qidirish',
    applicationSearch: 'Smena yoki tashkilot bo‘yicha qidirish',
    allShifts: 'Barcha smenalar',
    shown: 'Ko‘rsatilgan arizalar',
    results: 'ta natija',
    reset: 'Filtrlarni tozalash',
    noResults: 'Bu filtrga mos ariza yo‘q',
    noResultsText: 'Boshqa holat yoki smenani tanlang, yoxud qidiruvni tozalang.',
    noApplications: 'Birinchi arizangizdan boshlang',
    noApplicationsText:
      'Qulay smenani toping va ariza yuboring. Javob va takliflar shu yerda ko‘rinadi.',
    noCandidates: 'Nomzodlar shu yerda ko‘rinadi',
    noCandidatesText:
      'E’lon qilingan smenalarga ishchilar ariza yuborgach, ularni shu yerdan boshqarasiz.',
    viewProfile: 'Nomzod profilini ko‘rish',
    profile: 'Nomzod profili',
    experience: 'Tajriba haqida',
    roles: 'Ish yo‘nalishlari',
    languages: 'Tillar',
    skills: 'Ko‘nikmalar',
    notProvided: 'Ma’lumot kiritilmagan',
    note: 'Ariza izohi',
    appliedFor: 'Ariza yuborilgan smena',
    selfReported: 'Ishchi ko‘rsatgan',
    verifiedSkill: 'Tekshirilgan',
    privacy:
      'Bu profil ushbu ariza doirasida ko‘rsatilmoqda. Shaxsiy hujjatlar va telefon raqami bu yerda ochilmaydi.',
    submittedHelp: 'Arizangiz ish beruvchining qarorini kutmoqda.',
    shortlistedHelp: 'Arizangiz ko‘rib chiqilmoqda. Javobni shu yerdan kuzating.',
    offeredHelp: 'Taklif tafsilotlarini ko‘rib, muddati tugashidan oldin qaror qiling.',
    acceptedHelp:
      'Taklif qabul qilingan. Amaldagi holat va davomatni tasdiqlangan smenalardan tekshiring.',
    rejectedHelp: 'Ish beruvchi bu arizani rad etdi. Boshqa smenalarni ko‘rishingiz mumkin.',
    withdrawnHelp: 'Bu arizani qaytarib olgansiz.',
    expiredHelp: 'Bu ariza yoki taklifning muddati tugagan.',
    unavailableHelp: 'Smena uchun taklif yuborish vaqti tugagan yoki smena ochiq emas.',
    expiredOffer: 'Taklif muddati tugagan',
    profileLink: 'Profilimni ko‘rish',
    companyProfile: 'Tashkilot profili',
    dashboardTitle: 'Ish va rejalaringiz',
    dashboardText: 'Takliflar, smenalar va profilingiz — keyingi qadam aniq.',
    profileReady: 'Profilingizni boyiting',
    profileHint:
      'Kasblar, ko‘nikmalar va tajribangiz ish beruvchiga tanlov qilishda yordam beradi.',
    pendingOffers: 'Javobingiz kutilmoqda',
    pendingOffersText: 'Takliflar muddati tugashidan oldin shartlarni ko‘rib chiqing.',
    reviewOffers: 'Takliflarni ko‘rish',
    inProgress: 'Jarayondagi arizalar',
    nextShift: 'Yaqin smenalar',
    quickAccess: 'Tezkor amallar',
    manageTime: 'Bo‘sh vaqtni belgilash',
    manageTimeHint: 'Ishga qachon chiqishingizni belgilang.',
    saved: 'Saqlangan smenalar',
    savedHint: 'Yoqtirgan e’lonlarga qayting.',
    applicationsHint: 'Javoblar va ariza holatlarini kuzating.',
    noUpcoming: 'Hozircha rejalashtirilgan smena yo‘q',
    noUpcomingText: 'Taklifni qabul qilganingizdan keyin smena shu yerda paydo bo‘ladi.',
    searchForCity: 'Shahringizdagi smenalar',
    companyWorkspace: 'Tashkilot ish maydoni',
    companyIntro: 'Profil, nomzodlar va smenalarni bitta joydan boshqaring.',
    companyProfileHint: 'Kompaniya tavsifi, aloqa ma’lumotlari va filiallar.',
    candidatesHint: 'Nomzodlarning tajribasi va ko‘nikmalarini solishtiring.',
    calendarHint: 'Smenalar va band qilingan joylarni kuzating.',
    loading: 'Yuklanmoqda',
    recentLimit: 'Ro‘yxat so‘nggi arizalarni ko‘rsatadi.',
  },
  ru: {
    candidates: 'Кандидаты',
    candidateIntro: 'Сравните отклики, откройте профиль и выберите следующий шаг.',
    applicationsIntro: 'Статус каждого отклика и следующий шаг — в одном месте.',
    all: 'Все',
    active: 'В работе',
    offers: 'Предложения',
    accepted: 'Подтверждённые',
    closed: 'Завершённые',
    candidateSearch: 'Поиск по имени, опыту или смене',
    applicationSearch: 'Поиск по смене или компании',
    allShifts: 'Все смены',
    shown: 'Показанные отклики',
    results: 'результатов',
    reset: 'Сбросить фильтры',
    noResults: 'Нет откликов по этим фильтрам',
    noResultsText: 'Выберите другой статус или смену либо очистите поиск.',
    noApplications: 'Начните с первого отклика',
    noApplicationsText:
      'Найдите удобную смену и откликнитесь. Ответы и предложения появятся здесь.',
    noCandidates: 'Здесь появятся кандидаты',
    noCandidatesText:
      'Когда работники откликнутся на опубликованные смены, вы сможете управлять откликами здесь.',
    viewProfile: 'Посмотреть профиль кандидата',
    profile: 'Профиль кандидата',
    experience: 'Об опыте',
    roles: 'Направления работы',
    languages: 'Языки',
    skills: 'Навыки',
    notProvided: 'Информация не указана',
    note: 'Комментарий к отклику',
    appliedFor: 'Отклик на смену',
    selfReported: 'Указан работником',
    verifiedSkill: 'Проверен',
    privacy:
      'Профиль доступен в рамках этого отклика. Личные документы и номер телефона здесь не раскрываются.',
    submittedHelp: 'Отклик ожидает решения работодателя.',
    shortlistedHelp: 'Отклик рассматривается. Следите за ответом здесь.',
    offeredHelp: 'Изучите условия и ответьте до истечения срока предложения.',
    acceptedHelp:
      'Предложение принято. Текущий статус и посещаемость смотрите в подтверждённых сменах.',
    rejectedHelp: 'Работодатель отклонил этот отклик. Вы можете посмотреть другие смены.',
    withdrawnHelp: 'Вы отозвали этот отклик.',
    expiredHelp: 'Срок отклика или предложения истёк.',
    unavailableHelp: 'Смена закрыта для новых предложений или уже началась.',
    expiredOffer: 'Срок предложения истёк',
    profileLink: 'Мой профиль',
    companyProfile: 'Профиль компании',
    dashboardTitle: 'Ваша работа и планы',
    dashboardText: 'Предложения, смены и профиль — следующий шаг понятен.',
    profileReady: 'Дополните профиль',
    profileHint: 'Направления работы, навыки и опыт помогут работодателю сделать выбор.',
    pendingOffers: 'Ожидают вашего ответа',
    pendingOffersText: 'Изучите условия до истечения срока предложений.',
    reviewOffers: 'Посмотреть предложения',
    inProgress: 'Отклики в работе',
    nextShift: 'Ближайшие смены',
    quickAccess: 'Быстрые действия',
    manageTime: 'Указать свободное время',
    manageTimeHint: 'Отметьте, когда готовы выходить на работу.',
    saved: 'Сохранённые смены',
    savedHint: 'Вернитесь к понравившимся объявлениям.',
    applicationsHint: 'Следите за ответами и статусами откликов.',
    noUpcoming: 'Пока нет запланированных смен',
    noUpcomingText: 'После принятия предложения смена появится здесь.',
    searchForCity: 'Смены в вашем городе',
    companyWorkspace: 'Рабочее пространство компании',
    companyIntro: 'Управляйте профилем, кандидатами и сменами в одном месте.',
    companyProfileHint: 'Описание компании, контакты и филиалы.',
    candidatesHint: 'Сравнивайте опыт и навыки кандидатов.',
    calendarHint: 'Следите за сменами и занятыми местами.',
    loading: 'Загрузка',
    recentLimit: 'Список показывает последние отклики.',
  },
} as const;
